name: Update Visitor Counter

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch: # Allow manual trigger
  page_build: # Run when pages are built/deployed

permissions:
  contents: write # This is crucial - explicitly grant write permission

jobs:
  update-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Update visitor count
        run: |
          mkdir -p public/api

          if [ -f public/api/visitors.json ]; then
            count=$(jq '.count' public/api/visitors.json)
            increment=$(( RANDOM % 7 + 3 ))
            newCount=$((count + increment))
          else
            newCount=587
          fi

          echo "{\"count\":$newCount,\"updated\":\"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"}" > public/api/visitors.json

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/api/visitors.json
          git commit -m "Update visitor count" || echo "No changes to commit"
          git push
